package icons;

import com.intellij.openapi.util.IconLoader;
import consulo.ui.image.Image;

/**
 * NOTE THIS FILE IS AUTO-GENERATED by the build/scripts/icons.gant
 * Don't repeat mistakes of others ;-)
 */
public class UIDesignerNewIcons {
  private static Image load(String path) {
    return IconLoader.getIcon(path, UIDesignerNewIcons.class);
  }

  public static final Image ToolWindow = load("/com/intellij/designer/icons/toolWindow.png"); // 13x13
}
